% update C
C = chi.*(C+ + dt*((chi_l).*ifftn(convolveInFourier_diff(fftn(C.*(chi_l)))) -...
    ((chi_l).*C).*ifftn(convolveInFourier_diff(fftn(chi_l))) + ...
    chi_l_pit.*ifftn(convolveInFourier_corr(fftn(chi_s))) -...
    chi_s.*ifftn(convolveInFourier_corr(fftn(chi_l_pit)))))+ (1 - chi).*w;